### ISSUE TITLE
Errors prerendering page

### ISSUE THREAD

**Issue by loleg** [playbern/www-playbern-ch#40]
These kind of errors are preventing a Vercel build at the moment:

---

- Error occurred prerendering page "/programs". Read more: https://nextjs.org/docs/messages/prerender-error
- Error occurred prerendering page "/posts". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Unable to fetch, please see our FAQ for more information: https://tina.io/docs/errors/faq/
        Errors: 
	Error querying file content/program/Sonntag---Workshops.mdx from collection program. Please run "tinacms audit" or add the --verbose option  for more info
    at TinaClient.request 

---

I ran a `yarn tinacms audit` - but no errors were detected:

```
Checking post collection. 11 Documents
Checking program collection. 9 Documents
Checking global collection. 1 Documents
Checking author collection. 4 Documents
Checking page collection. 9 Documents
✅ Audit passed
Done in 22.32s.
```

**Comment by loleg** [comment]
Please check what the problem could be with `content/program/Sonntag---Workshops.mdx`

**Comment by Ibrahim-Halil-Kuray** [comment]
They had created Sonntag---Workshops.mdx file to times. I did some changes [here:] (https://playbern.ch/admin#/~ ) but github still same and my changes does not reflected to playbern.ch. When I turn back to edit mode, the changes are still there.

**Comment by loleg** [comment]
It looks like it only affects the `main` branch, the identical code builds fine from `dev`.

We should signal this to Tina, and see if there's a way to rebuild the graph in the cloud console. I already tried clicking all the Advanced Options to no avail.

**Comment by loleg** [comment]
Solved by resetting the account.

See also https://github.com/tinacms/tinacms/issues/4176
